import type { Property } from "./types"

export const mockProperties: Property[] = [
  {
    id: 1,
    title: "Odunpazarı'nda Modern Daire",
    images: ["/modern-living-room.png", "/modern-kitchen.png", "/modern-bedroom.png"],
    videos: [],
    type: "konut",
    listingType: "satilik",
    category: "daire",
    rooms: "3+1",
    area: 135,
    price: 2850000,
    currency: "TRY",
    address: "Vişnelik Mahallesi, Atatürk Bulvarı No:45",
    city: "Eskişehir",
    district: "Odunpazarı",
    features: ["Asansör", "Güvenlik", "Otopark", "Doğalgaz", "Balkon", "Merkezi Sistem"],
    description:
      "Eskişehir'in merkezi konumunda, tüm ihtiyaçlara yakın modern daire. Yeni binada, güvenlikli site içerisinde.",
    createdAt: "2024-01-15",
    status: "aktif",
    floor: "7",
    buildingAge: 1,
    contactPhone: "0555 123 45 67",
  },
  {
    id: 2,
    title: "Tepebaşı'nda Satılık Rezidans",
    images: ["/luxury-apartment-view.png", "/modern-dining-room.png", "/spacious-balcony-view.png"],
    videos: [],
    type: "konut",
    listingType: "satilik",
    category: "residence",
    rooms: "4+1",
    area: 185,
    price: 4250000,
    currency: "TRY",
    address: "Arifiye Mahallesi, Süleyman Çakır Cd. No:14",
    city: "Eskişehir",
    district: "Tepebaşı",
    features: ["Havuz", "Spor Salonu", "Güvenlik", "Kapalı Otopark", "Asansör", "Sauna", "Jakuzi"],
    description: "Reis Emlak ofisine çok yakın, lüks rezidans projesi. Sosyal olanakları bol, modern yaşam alanı.",
    createdAt: "2024-01-18",
    status: "aktif",
    floor: "12",
    buildingAge: 0,
    contactPhone: "0555 234 56 78",
  },
  {
    id: 3,
    title: "Bahçelievler'de Kiralık Daire",
    images: ["/modern-living-room.png", "/compact-modern-kitchen.jpg", "/cozy-bedroom-space.jpg"],
    videos: [],
    type: "konut",
    listingType: "kiralik",
    category: "daire",
    rooms: "2+1",
    area: 95,
    price: 15000,
    currency: "TRY",
    address: "Gültepe Mahallesi, 71. Sokak No:23",
    city: "Eskişehir",
    district: "Tepebaşı",
    features: ["Asansör", "Doğalgaz", "Balkon", "Otopark"],
    description: "Bahçelievler bölgesinde kiralık daire. Ulaşım ve alışveriş merkezlerine yakın.",
    createdAt: "2024-01-20",
    status: "aktif",
    floor: "4",
    buildingAge: 8,
    contactPhone: "0555 345 67 89",
  },
  {
    id: 4,
    title: "Çamlıca'da Havuzlu Villa",
    images: ["/modern-family-house.jpg", "/modern-home-garden.jpg", "/contemporary-living-space.png"],
    videos: [],
    type: "konut",
    listingType: "satilik",
    category: "villa",
    rooms: "5+",
    area: 280,
    price: 8500000,
    currency: "TRY",
    address: "Çamlıca Mahallesi, 15. Sokak No:8",
    city: "Eskişehir",
    district: "Odunpazarı",
    features: ["Havuz", "Geniş Bahçe", "Barbekü Alanı", "Kapalı Otopark", "Güvenlik Kamerası", "Jeneratör"],
    description: "Çamlıca'nın sakin semtinde müstakil havuzlu villa. Geniş bahçe ve modern mimarisi ile.",
    createdAt: "2024-01-22",
    status: "aktif",
    buildingAge: 2,
    contactPhone: "0555 456 78 90",
  },
  {
    id: 5,
    title: "Emek Mahallesi'nde Müstakil Ev",
    images: ["/detached-house-exterior.jpg", "/house-garden-view.jpg", "/family-home-interior.jpg"],
    videos: [],
    type: "konut",
    listingType: "satilik",
    category: "mustakil-ev",
    rooms: "4+2",
    area: 220,
    price: 5200000,
    currency: "TRY",
    address: "Emek Mahallesi, 34. Sokak No:12",
    city: "Eskişehir",
    district: "Tepebaşı",
    features: ["Bahçe", "Otopark", "Doğalgaz", "Alarm Sistemi", "Teras"],
    description: "Emek Mahallesi'nde bahçeli müstakil ev. Ailelere ideal, sakin bir semtte.",
    createdAt: "2024-01-24",
    status: "aktif",
    buildingAge: 12,
    contactPhone: "0555 567 89 01",
  },
  {
    id: 6,
    title: "Organize Sanayi Bölgesi Yakını İmarlı Arsa",
    images: ["/land-plot-aerial.jpg", "/empty-land-view.jpg"],
    videos: [],
    type: "arsa",
    listingType: "satilik",
    category: "arsa",
    area: 750,
    price: 2250000,
    currency: "TRY",
    address: "Hoşnudiye Mahallesi, 567. Sokak",
    city: "Eskişehir",
    district: "Tepebaşı",
    features: ["İmarlı", "Elektrik", "Su", "Yola Cepheli", "Sanayi Bölgesine Yakın"],
    description: "Organize Sanayi Bölgesi yakınında ticari imarlı arsa. Yatırım için ideal.",
    createdAt: "2024-01-25",
    status: "aktif",
    contactPhone: "0555 678 90 12",
  },
  {
    id: 7,
    title: "Yenikent'te Kiralık Residence",
    images: ["/luxury-apartment-view.png", "/modern-dining-room.png", "/spacious-balcony-view.png"],
    videos: [],
    type: "konut",
    listingType: "kiralik",
    category: "residence",
    rooms: "3+2",
    area: 165,
    price: 28000,
    currency: "TRY",
    address: "Yenikent Mahallesi, Üniversite Caddesi No:89",
    city: "Eskişehir",
    district: "Odunpazarı",
    features: ["Güvenlik", "Kapalı Otopark", "Asansör", "Havuz", "Spor Salonu", "Çocuk Oyun Alanı"],
    description: "Yenikent'te lüks rezidans dairesi. Üniversiteye ve şehir merkezine yakın.",
    createdAt: "2024-01-26",
    status: "aktif",
    floor: "9",
    buildingAge: 3,
    contactPhone: "0555 789 01 23",
  },
  {
    id: 8,
    title: "Şarhöyük'te Satılık Arsa",
    images: ["/land-plot-aerial.jpg", "/empty-land-view.jpg"],
    videos: [],
    type: "arsa",
    listingType: "satilik",
    category: "arsa",
    area: 500,
    price: 1750000,
    currency: "TRY",
    address: "Şarhöyük Mahallesi, 23. Sokak",
    city: "Eskişehir",
    district: "Tepebaşı",
    features: ["İmarlı", "Elektrik", "Su", "Köşe Parsel", "Konut İmarlı"],
    description: "Şarhöyük'te konut imarlı arsa. Villa yapımına uygun, sakin konum.",
    createdAt: "2024-01-27",
    status: "rezerve",
    contactPhone: "0555 890 12 34",
  },
  {
    id: 9,
    title: "Sütlüce'de Bahçeli Müstakil Ev",
    images: ["/detached-house-exterior.jpg", "/house-garden-view.jpg", "/family-home-interior.jpg"],
    videos: [],
    type: "konut",
    listingType: "kiralik",
    category: "mustakil-ev",
    rooms: "3+1",
    area: 180,
    price: 22000,
    currency: "TRY",
    address: "Sütlüce Mahallesi, Kuşkaya Sokak No:67",
    city: "Eskişehir",
    district: "Odunpazarı",
    features: ["Bahçe", "Otopark", "Doğalgaz", "Balkon", "Teras"],
    description: "Sütlüce'de bahçeli müstakil ev. Ailelere uygun, doğayla iç içe.",
    createdAt: "2024-01-28",
    status: "aktif",
    buildingAge: 10,
    contactPhone: "0555 901 23 45",
  },
  {
    id: 10,
    title: "71 Evler'de Satılık Daire",
    images: ["/studio-apartment-interior.png", "/compact-modern-kitchen.jpg", "/modern-bedroom.png"],
    videos: [],
    type: "konut",
    listingType: "satilik",
    category: "daire",
    rooms: "2+1",
    area: 105,
    price: 2100000,
    currency: "TRY",
    address: "71 Evler Mahallesi, İstiklal Caddesi No:156",
    city: "Eskişehir",
    district: "Odunpazarı",
    features: ["Asansör", "Güvenlik", "Doğalgaz", "Balkon"],
    description: "71 Evler semtinde satılık daire. Ulaşım ve sosyal olanaklara yakın.",
    createdAt: "2024-01-29",
    status: "aktif",
    floor: "5",
    buildingAge: 15,
    contactPhone: "0555 012 34 56",
  },
]
